TENSOR INITIALIZATIONS

In [ ]:
import torch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.shape)
print(my_tensor.device)
print(my_tensor.requires_grad)
print(my_tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
cpu
True
torch.float32


In [ ]:
x=torch.empty(3,3)
x=torch.zeros(3,3)
x=torch.rand(3,3)
x=torch.ones((3,3))
x=torch.eye(3)
x=torch.arange(start=0, end = 5, step =1)
x=torch.linspace(start=0.1, end=1, steps=10)
x=torch.empty(size=(1,5)).normal_(mean=0, std=1)
y=torch.empty(size=(1,5)).uniform_(0,1)
x=torch.diag(torch.ones(3))

In [ ]:
print(x)
print(y)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.2903, 0.3433, 0.4391, 0.1101, 0.2681]])


CONVERSIONS

In [ ]:
tensor=torch.arange(4)
print(tensor.dtype)
print(tensor.bool())
print(tensor.short())
print(tensor.long(), tensor.long().dtype)
print(tensor.half())
print(tensor.float(), tensor.float().dtype)
print(tensor.double())

torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3]) torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.]) torch.float32
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
import numpy as np
np_arr = np.zeros((5,5))
tensor=torch.from_numpy(np_arr)
np_array_back=tensor.numpy()

TENSOR MATCH and COMPARISON OPERATIONs

In [ ]:
x=torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z1 = torch.empty(3)
z2 = torch.add(x,y)
z2 = x+y
z2=x-y
print(z2)

print(x**2)
x >0
x<0

tensor([-8, -6, -4])
tensor([1, 4, 9])


tensor([False, False, False])

In [ ]:
# Matrix Multiplication
x1 = torch.rand(2,5)
x2 = torch.rand(5,3)
print(x1)
print(x2)

tensor([[0.5100, 0.6349, 0.2464, 0.9132, 0.1308],
        [0.4863, 0.3923, 0.9055, 0.8890, 0.8338]])
tensor([[0.2064, 0.9186, 0.7522],
        [0.4358, 0.0254, 0.7221],
        [0.3643, 0.6891, 0.2805],
        [0.7568, 0.2911, 0.8025],
        [0.6759, 0.6264, 0.4577]])


In [ ]:
x3 = torch.mm(x1, x2)
x3 = x1.mm(x2)
x3 = torch.rand(3,3)

print(x3.matrix_power(3))

# element_wise multiplication
z = x3*torch.rand(3,3)
a = torch.dot(x, y)
a


tensor([[0.4465, 0.5174, 0.7096],
        [0.2319, 0.2633, 0.3725],
        [0.5933, 0.7180, 0.9518]])


In [ ]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

#Broadcasting
x1 = torch.rand(5,5)
x2 = torch.rand(1,5)

z = x1-x2
z = x1 ** x2




In [ ]:
# Other useful tensor Operations
x = torch.tensor([[-1,2,3], [2,3,4], [3,4,5]])
sum_x = torch.sum(x, dim =1)
print(sum_x)
values, indices = torch.max(x,dim =0)
print(values, indices)
values, indices = torch.min(x, dim = 1)
print(values, indices)
abs_x = torch.abs(x)
print(abs_x)
z = torch.argmax(x, dim =0)
print(z)
z=torch.argmin(x, dim=1)
print(z)
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)
z = torch.eq(x, torch.eye(3))
print(z)
sorted_x, indices = torch.sort(x, dim =0, descending = False)
print(sorted_x)
z= torch.clamp(x, min= 0)
print(z)
x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
z = torch.any(x)
print(z)
z=torch.all(x)
print(z)

tensor([ 4,  9, 12])
tensor([3, 4, 5]) tensor([2, 2, 2])
tensor([-1,  2,  3]) tensor([0, 0, 0])
tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
tensor([2, 2, 2])
tensor([0, 0, 0])
tensor([1.3333, 3.0000, 4.0000])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[-1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]])
tensor([[0, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
tensor(True)
tensor(False)


TENSOR INDEXING

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
print(x[0].shape)
print(x[:,0].shape)
print(x[2, 0:10])
x[0,0] = 100

torch.Size([25])
torch.Size([10])
tensor([0.7100, 0.7287, 0.4166, 0.3768, 0.5726, 0.7896, 0.9331, 0.1720, 0.1638,
        0.7484])


In [ ]:
#Fancy Indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x)
print(x[rows, cols])

tensor([2, 5, 8])
tensor([[0.6209, 0.0913, 0.7969, 0.9157, 0.7788],
        [0.7493, 0.6986, 0.4973, 0.9594, 0.4682],
        [0.6067, 0.2702, 0.3646, 0.5248, 0.0276]])
tensor([0.4682, 0.6209])


In [ ]:
#Advanced Indexing
x = torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x>8)])
print(x[x.remainder(2) == 0])


# useful operations
print(torch.where(x>5, x, x*2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.numel())

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
10


TENSOR RESHAPING

In [ ]:
x = torch.arange(9)
x_3x3 = x.view(3,3)
print(x_3x3)

y = x_3x3.t()
print(y.contiguous().view(9))
print(y.reshape(9))


x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1, x2), dim = 0).shape)
print(torch.cat((x1, x2), dim=1).shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
